-- DROP DATABASE GESTION_B;
-- CONSULTA DE LAS DESCRIPCIONES DE SECTOR, CIUDAD Y MUNICIPIOS RELACIONADOS
USE GESTION_B
SELECT 
    S.DESCRIPCION AS DESCRIPCION_SECTOR,
    C.DESCRIPCION AS DESCRIPCION_CIUDAD,
    M.DESCRIPCION AS DESCRIPCION_MUNICIPIO 
FROM CIUDAD C
 JOIN MUNICIPIO M 
    ON M.ID_CIUDAD = C.ID
 JOIN SECTOR S
    ON M.ID = S.ID_MUNICIPIO;