-- CREATE DATABASE GESTION_B;

USE GESTION_B
GO
CREATE TABLE CIUDAD (
        ID INT NOT NULL IDENTITY,
        DESCRIPCION VARCHAR(250),
        PRIMARY KEY (ID)
    )
CREATE TABLE MUNICIPIO (
        ID INT NOT NULL IDENTITY,
        DESCRIPCION VARCHAR(250),
        ID_CIUDAD INT
        PRIMARY KEY (ID),
        CONSTRAINT FK_ID_CIUDAD FOREIGN KEY (ID_CIUDAD)
        REFERENCES CIUDAD(ID)
        )
CREATE TABLE SECTOR (
        ID INT NOT NULL IDENTITY, 
        DESCRIPCION VARCHAR(250),
        ID_MUNICIPIO INT,
        PRIMARY KEY (ID),
        CONSTRAINT FK_ID_MUNICIPIO FOREIGN KEY (ID_MUNICIPIO)
        REFERENCES MUNICIPIO(ID)
    )
    CREATE TABLE DIRECCIONES (
        ID INT NOT NULL IDENTITY,
        ID_CIUDAD INT,
        ID_MUNICIPIO INT,
        ID_SECTOR INT,
        REFERENCIA VARCHAR(250),
        PRIMARY KEY (ID),
        CONSTRAINT FK_ID_CIUDAD_DIR FOREIGN KEY (ID_CIUDAD)
        REFERENCES CIUDAD(ID),
        CONSTRAINT FK_ID_MUNICIPIO_DIR FOREIGN KEY (ID_MUNICIPIO)
        REFERENCES MUNICIPIO(ID),
        CONSTRAINT FK_ID_SECTOR_DIR FOREIGN KEY (ID_SECTOR)
        REFERENCES SECTOR(ID)

    )
    CREATE TABLE CLIENTES (
        ID INT NOT NULL IDENTITY,
        NOMBRE_APELLIDO VARCHAR(50),
        CEDULA VARCHAR(12),
        ID_DIRECCION INT,
        PRIMARY KEY (ID),
        CONSTRAINT FK_ID_DIRECCION FOREIGN KEY (ID_DIRECCION)
        REFERENCES DIRECCIONES(ID)
        )